version: '2'
services:
  server:
    container_name: 'server'
    restart: 'always'
    build: .
    ports:
      - '8000:8000'
    links:
      - 'mongo'
  mongo:
    container_name: 'mongo'
    restart: 'always'
    image: 'mongo:latest'
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
